### ISSUE TITLE
Label textual que mostra qual é o tema ativo segundo o botão v-switch

### ISSUE THREAD

**Issue by kaiomudkt** [DiegoBulhoes/pokedex#12]
O botão switch é controlado por uma função responsável por mudar as cores controlando o tema atual do site,
e a label do botão switch esta com uma String fixa, 
assim, é necessário que a String da label que represente o estado atual do tema esteja de acordo com a mesma.

![image](https://user-images.githubusercontent.com/43382610/123003524-4d890780-d381-11eb-8a6b-172ca266dd8e.png)
![image](https://user-images.githubusercontent.com/43382610/123003546-55e14280-d381-11eb-91df-6f00cc49e11f.png)

**Comment by kendyyahiro** [comment]
Acho que essa issue poderia trazer uma melhora estética, pois esse padrão de tema dark com texto deixa a desejar um pouco. Seria  uma pequena mudança, porém deixando talvez com uma lua e um sol, invés de tema escuro e tema claro, respectivamente.
