### ISSUE TITLE
Adicionar Footer com as informações dos integrantes

### ISSUE THREAD

**Issue by kendyyahiro** [DiegoBulhoes/pokedex#15]
Reparei que quando chega ao final da página não apresenta nenhuma informação. Seria bastante interessante adicionarmos um rodapé para decorar e adicionar as informações dos integrantes para preencher visualmente além das buscas de Pokémon.

O propósito seria melhorar visualmente e demarcar o final da página.

**Comment by Vinny1892** [comment]
faltou adicionar  a label de  enhancement  para indicar que se tratava de uma melhoria no codigo

**Comment by kaiomudkt** [comment]
nas próximas versões podem ser adicionada mais informações ao rodapé,
e possivelmente adicionar a barra de busca para que a cliente não precise voltar ao inicio para poder buscar.

**Comment by DiegoBulhoes** [comment]
Nas próximas versões podem ser adicionado o GitHub dos colaboradores
