### ISSUE TITLE
Ao chegar no final da página, há uma demora grande na busca de novas opções de Pokémon

### ISSUE THREAD

**Issue by kendyyahiro** [DiegoBulhoes/pokedex#2]
Sempre que chega ao final da página, a aplicação não retorna uma resposta para o usuário enquanto está carregando mais opções de Pokémon. Isto é, fica complicado saber se está carregando mais informações ou se realmente finalizou o resultado. 

Para esse caso, podemos tentar melhorar a requisição da API, para torná-la mais eficiente ou simplesmente inserir um loading sempre que se aproximar do final da página com a intenção de mostrar para o usuário que a busca ainda está sendo feita e que mais resultados surgirão.

**Comment by Vinny1892** [comment]
qual navegador você esta usando ?

**Comment by Vinny1892** [comment]
O calculo feito aonde está o scroll do mouse  pode mudar ligeiramente dependendo do navegador a ser utilizado

**Comment by DiegoBulhoes** [comment]
Seria possível colocar uma gif? Dessa forma ficaria mais claro.

**Comment by SandimL** [comment]
Acredito que você poderia descrever melhor mostrando o passo a passo de como está ocorrendo

**Comment by kaiomudkt** [comment]
talvez o caminho mais simples seja o melhor para este caso, 
uma simples mensagem de texto ou ícone de load deve resolver
