### ISSUE TITLE
Não mostra mensagem de erro ou aviso caso pokemon não seja encontrado

### ISSUE THREAD

**Issue by Vinny1892** [DiegoBulhoes/pokedex#3]
Ao pesquisar o nome de algum pokemon, seja ele um pokemon que existe ou  não.  não é retornado feedback algum  se  retornou um pokemon  valido

abaixo um gif  que mostra a reprodução do bug
![pokemon](https://user-images.githubusercontent.com/41531003/122825966-9cb33780-d2b0-11eb-95e2-9d27e987445f.gif)

**Comment by SandimL** [comment]
Percebi esse problema hoje também

**Comment by kaiomudkt** [comment]
hum, nao tinha percebido esse erro, gostei do gif, fica bem explicativo
