### ISSUE TITLE
Pipeline no GitHub Actions

### ISSUE THREAD

**Issue by DiegoBulhoes** [DiegoBulhoes/pokedex#4]
Será necessário criar  uma pipeline com o proposito de criar uma imagem Docker e deixar publica no Docker Hub.

**Comment by SandimL** [comment]
Muito boa essa alteração para a robustez do projeto

**Comment by Vinny1892** [comment]
com esta imagem do docker irá facilitar  a ultilização desta aplicação por qualquer um que se interressar pelo assunto

**Comment by DiegoBulhoes** [comment]
Link do DockerHub

- https://hub.docker.com/repository/docker/diegobulhoes/pokedex

**Comment by kendyyahiro** [comment]
Massa! Isso teria me ajudado muito quando eu tinha começado a usar a aplicação
